### ISSUE TITLE
Error during build:  E: gnupg, gnupg2 and gnupg1 do not seem to be installed, but one of them is required for this operation

### ISSUE THREAD

**Issue by fama** [gdoteof/docker-streisand#10]
When running the command

`docker build -t streisand .`

I get the following error:

Sending build context to Docker daemon  157.2kB
Step 1/8 : FROM	debian
 ---> 0af60a5c6dd0
Step 2/8 : RUN	echo 'deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main' >> /etc/apt/sources.list 	&& apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367 	&& apt-get update && apt-get install -y 	git 	python-pip 	openssh-client 	python-dev 	ruby 	curl 	ansible
 ---> Running in 028258de6ed9
E: gnupg, gnupg2 and gnupg1 do not seem to be installed, but one of them is required for this operation
The command '/bin/sh -c echo 'deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main' >> /etc/apt/sources.list 	&& apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367 	&& apt-get update && apt-get install -y 	git 	python-pip 	openssh-client 	python-dev 	ruby 	curl 	ansible' returned a non-zero code: 255
Boriss-MBP:docker-streisand boris$ docker build -t streisand .
Sending build context to Docker daemon  157.2kB
Step 1/8 : FROM	debian
 ---> 0af60a5c6dd0
Step 2/8 : RUN	echo 'deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main' >> /etc/apt/sources.list 	&& apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367 	&& apt-get update && apt-get install -y 	git 	python-pip 	openssh-client 	python-dev 	ruby 	curl 	ansible
 ---> Running in 1236e6c6a577
E: gnupg, gnupg2 and gnupg1 do not seem to be installed, but one of them is required for this operation
The command '/bin/sh -c echo 'deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main' >> /etc/apt/sources.list 	&& apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367 	&& apt-get update && apt-get install -y 	git 	python-pip 	openssh-client 	python-dev 	ruby 	curl 	ansible' returned a non-zero code: 255

This can be fixed by adding gnupg2 to the build command:

```FROM	debian

# For Ansible v2, from https://docs.ansible.com/ansible/intro_installation.html#latest-releases-via-apt-debian

RUN apt-get update && apt-get install -y gnupg2

RUN	echo 'deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main' >> /etc/apt/sources.list \
	&& apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367 \
	&& apt-get update && apt-get install -y \
	gnupg2 \
	git \
	python-pip \
	openssh-client \
	python-dev \
	ruby \
	curl \
	ansible

ENV	HOME	/root
RUN	ssh-keygen -f /root/.ssh/id_rsa -q -N "" \
	&& pip install markupsafe dopy boto linode-python pyrax

WORKDIR	/root

RUN	git clone https://github.com/jlund/streisand.git

WORKDIR	/root/streisand

CMD	["./streisand"]
```

**Comment by gdoteof** [comment]
Just pushed a fix.  Thanks for opening the issue.
