### ISSUE TITLE
Tunnelblick & SSH Timing

### ISSUE THREAD

**Issue by davesgonechina** [gdoteof/docker-streisand#3]
Often getting this error at GATHERING FACTS when using an existing SSH key

> SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh

This might be solved by waiting for an ssh connection, see https://github.com/geerlingguy/ansible-for-devops/issues/3

Later in the process, getting this fatal error which appears to point to a deprecated version of Tunnelblick that isn't in the latest version of jlund/streisand, which points to 3.5.2 (https://github.com/jlund/streisand/blob/cc0936e1220a0d7512e4a5504dac7ad22b926716/playbooks/roles/streisand-mirror/vars/openvpn.yml)

> TASK: [streisand-mirror | Mirror Tunnelblick for OS X] ***********************\* 
> failed: [45.55.12.61] => {"dest": "/var/www/streisand/mirror/openvpn", "failed": true, "gid": 33, "group": "www-data", "mode": "0755", "owner": "www-data", "response": "Request failed: <urlopen error [Errno -2] Name or service not known>", "size": 4096, "state": "directory", "status_code": -1, "uid": 33, "url": "http://softlayer-ams.dl.sourceforge.net/project/tunnelblick/All%20files/Tunnelblick_3.4.1_r3054.dmg"}
> msg: Request failed
> FATAL: all hosts have already failed -- aborting

**Comment by Dimtree** [comment]
Probably better to report this to https://github.com/jlund/streisand, this is just a docker image that clones the repo.
